interface ChinaP0SearchSeedEntry {
  id: string;
  occupationId: string;
  label: string;
  labelEn?: string;
  categoryLv1: string;
  categoryLv2: string;
  analysisTemplateId: string;
  searchPriority: number;
  aliases: string[];
}

export const CHINA_P0_SEARCH_SEEDS: ChinaP0SearchSeedEntry[] = [
  {
    id: "china:cross-border-e-commerce-operations-manager",
    occupationId: "13-1161.00",
    label: "跨境电商运营管理师",
    labelEn: "Cross-Border E-Commerce Operations Manager",
    categoryLv1: "运营",
    categoryLv2: "平台经济",
    analysisTemplateId: "soc:13-1161.00",
    searchPriority: 120,
    aliases: ["跨境电商运营管理师","跨境电商运营","跨境运营","跨境店铺运营","跨境电商运营经理"],
  },
  {
    id: "china:user-growth-operations-specialist",
    occupationId: "13-1161.00",
    label: "用户增长运营师",
    labelEn: "User Growth Operations Specialist",
    categoryLv1: "运营",
    categoryLv2: "平台经济",
    analysisTemplateId: "soc:13-1161.00",
    searchPriority: 120,
    aliases: ["用户增长运营师","增长运营","用户增长","增长负责人","流量增长运营"],
  },
  {
    id: "china:on-demand-delivery-rider",
    occupationId: "43-5021.00",
    label: "网约配送员",
    labelEn: "On-Demand Delivery Rider",
    categoryLv1: "运营",
    categoryLv2: "平台经济",
    analysisTemplateId: "soc:43-5021.00",
    searchPriority: 120,
    aliases: ["网约配送员","即时配送员","同城配送员","外卖骑手","配送骑手"],
  },
  {
    id: "china:bim-technician",
    occupationId: "17-3011.00",
    label: "BIM技术员",
    labelEn: "BIM Technician",
    categoryLv1: "技术",
    categoryLv2: "数字建造",
    analysisTemplateId: "soc:17-3011.00",
    searchPriority: 120,
    aliases: ["建筑信息模型技术员","BIM技术员","建筑信息模型师","BIM工程师","BIM建模师"],
  },
  {
    id: "china:carbon-emissions-administrator",
    occupationId: "13-1041.00",
    label: "碳排放管理员",
    labelEn: "Carbon Emissions Administrator",
    categoryLv1: "技术",
    categoryLv2: "绿色经济",
    analysisTemplateId: "soc:13-1041.00",
    searchPriority: 120,
    aliases: ["碳排放管理员","碳管理师","碳排放管理","碳盘查专员","碳核算管理员"],
  },
  {
    id: "china:ai-training-specialist",
    occupationId: "15-2051.00",
    label: "人工智能训练师",
    labelEn: "AI Training Specialist",
    categoryLv1: "技术",
    categoryLv2: "AI/数据",
    analysisTemplateId: "soc:15-2051.00",
    searchPriority: 120,
    aliases: ["人工智能训练师","AI训练师","数据标注师","模型训练师","人工智能标注师"],
  },
  {
    id: "china:generative-ai-application-specialist",
    occupationId: "15-1252.00",
    label: "生成式AI应用员",
    labelEn: "Generative AI Application Specialist",
    categoryLv1: "技术",
    categoryLv2: "AI/数据",
    analysisTemplateId: "soc:15-1252.00",
    searchPriority: 120,
    aliases: ["生成式人工智能系统应用员","生成式AI应用员","AIGC应用员","生成式AI应用师","大模型应用专员","AI应用员"],
  },
  {
    id: "china:information-security-testing-specialist",
    occupationId: "15-1212.00",
    label: "信息安全测试员",
    labelEn: "Information Security Testing Specialist",
    categoryLv1: "技术",
    categoryLv2: "AI/数据",
    analysisTemplateId: "soc:15-1212.00",
    searchPriority: 120,
    aliases: ["信息安全测试员","安全测试工程师","渗透测试员","安全测试专员","网络安全测试员"],
  },
  {
    id: "china:homestay-steward",
    occupationId: "39-6012.00",
    label: "民宿管家",
    labelEn: "Homestay Steward",
    categoryLv1: "运营",
    categoryLv2: "平台经济",
    analysisTemplateId: "soc:39-6012.00",
    searchPriority: 120,
    aliases: ["民宿管家","民宿运营管家","民宿主理人","民宿运营","民宿前台管家"],
  },
  {
    id: "china:supply-chain-manager",
    occupationId: "13-1081.00",
    label: "供应链管理师",
    labelEn: "Supply Chain Manager",
    categoryLv1: "物流",
    categoryLv2: "产业运营",
    analysisTemplateId: "soc:13-1081.00",
    searchPriority: 120,
    aliases: ["供应链管理师","供应链运营师","供应链经理","供应链专员","供应链规划"],
  },
  {
    id: "china:digital-twin-application-technician",
    occupationId: "15-1252.00",
    label: "数字孪生应用技术员",
    labelEn: "Digital Twin Application Technician",
    categoryLv1: "技术",
    categoryLv2: "AI/数据",
    analysisTemplateId: "soc:15-1252.00",
    searchPriority: 120,
    aliases: ["数字孪生应用技术员","数字孪生技术员","数字孪生工程师","孪生应用工程师","数字孪生实施"],
  },
  {
    id: "china:carbon-sink-measurement-and-assessment-specialist",
    occupationId: "19-2041.00",
    label: "碳汇计量评估师",
    labelEn: "Carbon Sink Measurement and Assessment Specialist",
    categoryLv1: "技术",
    categoryLv2: "绿色经济",
    analysisTemplateId: "soc:19-2041.00",
    searchPriority: 120,
    aliases: ["碳汇计量评估师","碳汇评估师","碳汇计量师","碳汇核算师","碳汇项目评估"],
  },
  {
    id: "china:family-education-guidance-specialist",
    occupationId: "21-1012.00",
    label: "家庭教育指导师",
    labelEn: "Family Education Guidance Specialist",
    categoryLv1: "教育医疗",
    categoryLv2: "家庭服务",
    analysisTemplateId: "soc:21-1012.00",
    searchPriority: 120,
    aliases: ["家庭教育指导师","家庭教育顾问","家庭教育咨询师","家教指导师","亲子教育指导"],
  },
  {
    id: "china:elderly-functional-assessment-specialist",
    occupationId: "21-1093.00",
    label: "老年人能力评估师",
    labelEn: "Elderly Functional Assessment Specialist",
    categoryLv1: "教育医疗",
    categoryLv2: "健康照护",
    analysisTemplateId: "soc:21-1093.00",
    searchPriority: 120,
    aliases: ["老年人能力评估师","老年能力评估师","老年评估师","失能评估师","养老评估师"],
  },
  {
    id: "china:birth-defect-prevention-counselor",
    occupationId: "29-9092.00",
    label: "出生缺陷防控咨询师",
    labelEn: "Birth Defect Prevention Counselor",
    categoryLv1: "教育医疗",
    categoryLv2: "健康照护",
    analysisTemplateId: "soc:29-9092.00",
    searchPriority: 120,
    aliases: ["出生缺陷防控咨询师","出生缺陷咨询师","优生咨询师","出生缺陷防控","产前防控咨询"],
  },
  {
    id: "china:assistive-technology-consultant",
    occupationId: "21-1015.00",
    label: "康复辅助技术咨询师",
    labelEn: "Assistive Technology Consultant",
    categoryLv1: "教育医疗",
    categoryLv2: "健康照护",
    analysisTemplateId: "soc:21-1015.00",
    searchPriority: 120,
    aliases: ["康复辅助技术咨询师","辅具咨询师","康复辅具咨询师","辅助技术咨询师","辅具适配师"],
  },
  {
    id: "china:agricultural-digitalization-technician",
    occupationId: "19-4012.00",
    label: "农业数字化技术员",
    labelEn: "Agricultural Digitalization Technician",
    categoryLv1: "其他",
    categoryLv2: "数字农业",
    analysisTemplateId: "soc:19-4012.00",
    searchPriority: 120,
    aliases: ["农业数字化技术员","数字农业技术员","智慧农业技术员","农业数字化专员","数字农技员"],
  },
  {
    id: "china:blockchain-application-operator",
    occupationId: "15-1299.00",
    label: "区块链应用操作员",
    labelEn: "Blockchain Application Operator",
    categoryLv1: "技术",
    categoryLv2: "AI/数据",
    analysisTemplateId: "soc:15-1299.00",
    searchPriority: 120,
    aliases: ["区块链应用操作员","区块链操作员","链上应用操作员","区块链运营专员","链上业务操作员"],
  },
];
